language: node_js

node_js:
  - "16.10.0"

install:
  - npm install

script:
    - npm test
    - npm run build

after_success:
  - sudo apt-get install sshpass 
  - find build/* -type f -exec curl -u $FTP_USER:$FTP_PASS --ftp-create-dirs -T {} sftp://$FTP_URL \;