language: node_js

node_js:
  - "16.10.0"

install:
  - npm install

script:
    - npm test
    - npm run build
  
addons:
  apt:
    packages:
    - sshpass

after_success:
  - sshpass -p $FTP_PASS scp -r build/* $FTP_USER@$FTP_URL