language: node_js

node_js:
  - "16.10.0"

install:
  - npm install

script:
    - npm test
    - npm run build
  
before_install:
  - sudo apt-get -y install sshpass

addons:
  apt:
    update: true

after_success:
  - test $TRAVIS_BRANCH = "main" && sshpass -p $SSH_PASS scp -o stricthostkeychecking=no -r build/* $SSH_USER@$SSH_SERVER:$WEB_PATH