language: node_js

node_js:
  - "16.10.0"

install:
  - npm install

script:
    - npm test
    - npm run build
  
before_install:
  - sudo apt-get -y install sshpass

addons:
  apt:
    update: true

after_success:
  - sshpass -p $FTP_PASS scp -o stricthostkeychecking=no -r build/* $FTP_USER@$FTP_URL